"""
Django settings for oficina_prj project.

Generated by 'django-admin startproject' using Django.
"""

import os
from pathlib import Path
import dj_database_url  # Biblioteca para conectar ao banco do Render

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CONFIGURAÇÕES DE SEGURANÇA PARA O RENDER ---

# Pega a chave secreta do ambiente (Render) ou usa uma padrão insegura para testes locais
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-chave-reserva-para-teste-local')

# Se a variável RENDER existir, DEBUG vira False (Produção). Senão, True (Local).
DEBUG = 'RENDER' not in os.environ

# Permite acesso de qualquer lugar (necessário para o Render)
ALLOWED_HOSTS = ['*']

# ------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Seus Apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <--- WhiteNoise para arquivos estáticos no Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oficina_prj.urls'  # Ajustado para o nome da sua pasta

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Pasta de templates na raiz
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oficina_prj.wsgi.application' # Ajustado para o nome da sua pasta

# --- BANCO DE DADOS (SQLite local / PostgreSQL no Render) ---
DATABASES = {
    'default': dj_database_url.config(
        # Tenta usar o banco do Render, se não achar, usa o SQLite local
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# --- ARQUIVOS ESTÁTICOS (CSS, JS, IMAGENS) ---

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Compressão e cache de arquivos estáticos para o Render
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configuração de Upload de Imagens
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- CONFIGURAÇÕES DO SEU PROJETO (LOGIN/LOGOUT) ---

# Modelo de usuário personalizado
AUTH_USER_MODEL = 'core.User'

# Redirecionamentos
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Configuração para ID numérico automático
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'